name: Run MATLAB Script

on:
  push:
    branches:
      - main

jobs:
  run-matlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          matlab-version: 'R2021a'

      - name: Install MATLAB Toolbox
        run: matlab -batch "toolboxinstaller.install('signal')"

      - name: Run MATLAB Script
        uses: matlab-actions/run-matlab@v1
        with:
          script: hello.m
